Properly handle jq parsing error when handling CI publishing

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -136,14 +136,19 @@ publish:
     - |
       echo "Current tag is $CI_COMMIT_TAG"
       for file in sorted_artifacts/*; do
-        curl --request POST --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
+        response=$(curl --silent --request POST --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
           --form "file=@$file" \
-          "$CI_API_V4_URL/projects/$CI_PROJECT_ID/uploads" | jq -r '.url' | while read -r asset_url; do
-            curl --request POST --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
-              --header "Content-Type: application/json" \
-              --data "{ \"name\": \"$(basename $file)\", \"url\": \"$asset_url\" }" \
-              "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases/$CI_COMMIT_TAG/assets/links"
-          done
+          "$CI_API_V4_URL/projects/$CI_PROJECT_ID/uploads")
+        asset_url=$(echo "$response" | jq -er '.url' 2>/dev/null)
+        if [ $? -ne 0 ]; then
+          echo "Error: Failed to upload file $file. Response was: $UPLOAD_RESPONSE"
+          continue
+        fi
+        echo "Uploading file $file"
+        curl --request POST --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
+          --header "Content-Type: application/json" \
+          --data "{ \"name\": \"$(basename $file)\", \"url\": \"$asset_url\" }" \
+          "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases/$CI_COMMIT_TAG/assets/links"
       done
   tags:
     - macos
